from typing import List, Optional, Tuple

from mazemaster.datastructures.models_and_schemas import ExcelCoordinate
from mazemaster.solvers.gridmodels import Dimension, GridLocation


walldataset: List[Tuple[Dimension, GridLocation, List[str]]] = []

# 0
walldataset.append(
    (
        Dimension(8, 8),
        GridLocation(0, 0),
        [
            "C1",
            "G1",
            "A2",
            "C2",
            "E2",
            "G2",
            "C3",
            "E3",
            "B4",
            "C4",
            "E4",
            "F4",
            "G4",
            "B5",
            "E5",
            "B6",
            "D6",
            "E6",
            "G6",
            "H6",
            "B7",
            "D7",
            "G7",
            "B8",
        ],
    )
)

# 1
walldataset.append(
    (
        Dimension(10, 10),
        GridLocation(0, 0),
        [
            "E4",
            "E10",
            "D8",
            "F5",
            "F8",
            "I4",
            "I10",
            "A6",
            "C3",
            "I7",
            "B4",
            "B10",
            "G6",
            "D1",
            "F1",
            "D10",
            "F4",
            "I3",
            "F10",
            "J8",
            "I6",
            "A2",
            "A8",
            "I9",
            "A5",
            "B6",
            "H10",
            "E2",
            "E8",
            "E5",
            "J1",
            "F6",
            "J4",
            "I2",
            "I8",
            "J10",
            "B2",
            "A4",
            "J7",
            "A7",
            "C4",
            "C10",
            "B8",
            "C7",
            "H6",
            "G4",
            "G10",
            "H9",
        ],
    )
)

# 2
walldataset.append(
    (
        Dimension(10, 10),
        GridLocation(0, 0),
        [
            "E4",
            "E10",
            "D8",
            "F5",
            "F8",
            "I4",
            "I10",
            "A6",
            "C3",
            "I7",
            "B4",
            "B10",
            "G6",
            "D1",
            "F1",
            "F4",
            "I3",
            "F10",
            "J8",
            "I6",
            "A2",
            "A8",
            "I9",
            "A5",
            "B6",
            "H10",
            "E2",
            "E8",
            "E5",
            "J1",
            "F6",
            "J4",
            "I2",
            "I8",
            "J10",
            "B2",
            "A4",
            "J7",
            "A7",
            "C4",
            "C10",
            "B8",
            "C7",
            # "H6",
            "G4",
            "G10",
            # "H9",
        ],
    )
)

# 3
walldataset.append(
    (
        Dimension(10, 10),
        GridLocation(0, 0),
        [
            "E4",
            "E10",
            "D8",
            "F5",
            "F8",
            "I4",
            "I10",
            "A6",
            "C3",
            "I7",
            "B4",
            "B10",
            "G6",
            "D1",
            "F1",
            "F4",
            "I3",
            "F10",
            "J8",
            "I6",
            "A2",
            "A8",
            "I9",
            "A5",
            "B6",
            "H10",
            "E2",
            "E8",
            "E5",
            "J1",
            "F6",
            "J4",
            "I2",
            "I8",
            "J10",
            "B2",
            "A4",
            "J7",
            "A7",
            "C4",
            "C10",
            "B8",
            "H6",
            "G4",
            "G10",
            "H9",
        ],
    )
)

# 4
walldataset.append(
    (
        Dimension(width=10, height=10),
        GridLocation(0, 0),
        [
            "E1",
            "D5",
            "E4",
            "D8",
            "F2",
            "I1",
            "F8",
            "J6",
            "I10",
            "I7",
            "C3",
            "B1",
            "B4",
            "B10",
            "C9",
            "H5",
            "G3",
            "G6",
            "D4",
            "F1",
            "F7",
            "D10",
            "F4",
            "F10",
            "J8",
            "I6",
            "A8",
            "C5",
            "B3",
            "I9",
            "C8",
            "H1",
            "H10",
            "G8",
            "E2",
            "D6",
            "I2",
            "J10",
            "A10",
            "B5",
            "C10",
            "B8",
            "H3",
            "G7",
            "G10",
        ],
    )
)

# 5
walldataset.append(
    (
        Dimension(width=10, height=10),
        GridLocation(0, 0),
        [
            "D5",
            "E4",
            "D2",
            "E10",
            "F2",
            "J3",
            "C3",
            "B10",
            "H5",
            "G3",
            "D10",
            "F10",
            "J2",
            "A8",
            "C5",
            "A5",
            "B6",
            "H10",
            "E8",
            "D6",
            "J1",
            "F6",
            "I5",
            "D9",
            "I2",
            "J10",
            "B2",
            "A10",
            "B5",
            "C10",
            "G1",
            "H6",
            "G10",
            "H9",
        ],
    )
)

# exitlocation[when multiple, then only one], exitcount, shortestpath, longestpath
solutions: List[Tuple[Optional[GridLocation], int, List[str], List[str]]] = [
    (
        GridLocation(col=0, row=7),
        1,
        ["A1", "B1", "B2", "B3", "A3", "A4", "A5", "A6", "A7", "A8"],
        ["A1", "B1", "B2", "B3", "A3", "A4", "A5", "A6", "A7", "A8"],
    ),
    (
        GridLocation(col=0, row=9),
        1,
        [
            "A1",
            "B1",
            "C1",
            "C2",
            "D2",
            "D3",
            "D4",
            "D5",
            "D6",
            "E6",
            "E7",
            "F7",
            "G7",
            "G8",
            "G9",
            "F9",
            "E9",
            "D9",
            "C9",
            "B9",
            "A9",
            "A10",
        ],
        [
            "A1",
            "B1",
            "C1",
            "C2",
            "D2",
            "D3",
            "D4",
            "D5",
            "C5",
            "C6",
            "D6",
            "D7",
            "E7",
            "F7",
            "G7",
            "H7",
            "H8",
            "G8",
            "G9",
            "F9",
            "E9",
            "D9",
            "C9",
            "B9",
            "A9",
            "A10",
        ],
    ),
    (
        GridLocation(col=3, row=9),
        2,
        [
            "A1",
            "B1",
            "C1",
            "C2",
            "D2",
            "D3",
            "D4",
            "D5",
            "D6",
            "E6",
            "E7",
            "F7",
            "G7",
            "G8",
            "G9",
            "F9",
            "E9",
            "D9",
            "D10",
        ],
        None,
    ),
    (
        GridLocation(col=3, row=9),
        2,
        ["A1", "B1", "C1", "C2", "D2", "D3", "D4", "D5", "C5", "C6", "C7", "C8", "C9", "D9", "D10"],
        None,
    ),
    (
        GridLocation(col=4, row=9),
        1,
        ["A1", "A2", "A3", "A4", "A5", "A6", "B6", "C6", "C7", "D7", "E7", "E8", "E9", "E10"],
        ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "B7", "B6", "C6", "C7", "D7", "E7", "E8", "E9", "E10"],
    ),
    (
        GridLocation(col=8, row=9),
        1,
        ["A1", "B1", "C1", "D1", "E1", "E2", "E3", "F3", "F4", "G4", "G5", "G6", "G7", "H7", "I7", "I8", "I9", "I10"],
        [
            "A1",
            "A2",
            "A3",
            "A4",
            "B4",
            "C4",
            "D4",
            "D3",
            "E3",
            "F3",
            "F4",
            "F5",
            "E5",
            "E6",
            "E7",
            "F7",
            "F8",
            "F9",
            "G9",
            "G8",
            "H8",
            "I8",
            "I7",
            "H7",
            "G7",
            "G6",
            "G5",
            "G4",
            "H4",
            "H3",
            "I3",
            "I4",
            "J4",
            "J5",
            "J6",
            "J7",
            "J8",
            "J9",
            "I9",
            "I10",
        ],
    ),
]
